CREATE SCHEMA IF NOT EXISTS `zup` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `zup`;

DROP TABLE IF EXISTS `PRODUCT`;

CREATE TABLE IF NOT EXISTS `PRODUCT` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NAME` VARCHAR(100) NOT NULL,
  `DESCRIPTION` VARCHAR(100) NOT NULL,
  `CATEGORY` VARCHAR(100) NOT NULL,
  `PRICE` DOUBLE NOT NULL,
  `CHANGE_DATE` TIMESTAMP NOT NULL

)ENGINE = InnoDB;;
