CREATE TABLE product (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(100) NOT NULL,
  category VARCHAR(100) NOT NULL,
  price DOUBLE NOT NULL,
  change_date TIMESTAMP NOT NULL
);
